version: '3.1'

services:
  back:
    build: ./back
    container_name: back
    ports:
      - 3001:3001
    networks:
      - my-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - ${MONGODB_PORT}:${MONGODB_DOCKER_PORT}
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - .env

  front:
    build: ./front
    container_name: front
    ports:
      - 8080:80
    networks:
      - my-network

networks:
  my-network: